backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "springkastelen"
    label: "Springkastelen"
    files:
      - file: "content/springkastelen.json"
        label: "Aanbod"
        name: "aanbod"
        fields:
          - label: "Springkastelen"
            name: "items"
            widget: "list"
            fields:
              - { label: "Naam", name: "name", widget: "string" }
              - { label: "Beschrijving", name: "description", widget: "text" }
              - { label: "Prijs", name: "price", widget: "string", required: false }
              - { label: "Capaciteit", name: "capacity", widget: "string", required: false }
              - { label: "Afbeelding", name: "image", widget: "image", required: false }